"use client";
import { useState, useTransition } from "react";
import { changeCustomerPassword, deleteCustomerAddress, saveCustomerAddress, saveCustomerProfile } from "@/lib/actions";
import { chileRegions } from "@/lib/shipping";
import { citiesForRegion } from "@/lib/chile-address";
import { PasswordField } from "@/components/password-field";

type Address={id:string;label:string;region:string;city:string;street:string;streetNumber:string;detail:string;isDefault:boolean};
export function AccountSettings({name,phone,addresses}:{name:string;phone:string;addresses:Address[]}){
 const [busy,start]=useTransition();const [notice,setNotice]=useState("");const [error,setError]=useState("");const [draft,setDraft]=useState<Address|null|"new">(null);const [region,setRegion]=useState(addresses[0]?.region||chileRegions[0].name);
 const feedback=(r:{ok:boolean;message?:string})=>{setError(r.ok?"":r.message||"No se pudo guardar.");setNotice(r.ok?r.message||"Guardado.":"");};
 const regionId=chileRegions.find(r=>r.name===region)?.id||"aysen";
 return <section className="account-settings"><h2>Mis datos</h2><form className="account-settings-form" action={(fd)=>start(async()=>feedback(await saveCustomerProfile(fd)))}><label>Nombre<input name="name" defaultValue={name} required minLength={2}/></label><label>Teléfono<input name="phone" type="tel" defaultValue={phone} required minLength={6}/></label><button className="soft-button dark" disabled={busy}>Guardar mis datos</button></form>
 <h2>Direcciones de envío</h2>{addresses.map(a=><article className="saved-address" key={a.id}><div><strong>{a.label}{a.isDefault?" · Predeterminada":""}</strong><p>{a.street} {a.streetNumber}{a.detail?`, ${a.detail}`:""}, {a.city}, {a.region}</p></div><div className="table-actions"><button className="mini-action" onClick={()=>{setDraft(a);setRegion(a.region)}}>Editar</button><button className="mini-action danger-action" disabled={busy} onClick={()=>start(async()=>feedback(await deleteCustomerAddress(a.id)))}>Eliminar</button></div></article>)}<button className="mini-action" onClick={()=>{setRegion(chileRegions[0].name);setDraft("new")}}>+ Agregar dirección</button>
 {draft!==null&&<form key={draft==="new"?"new":draft.id} className="account-address-form" action={(fd)=>start(async()=>{const r=await saveCustomerAddress(fd);feedback(r);if(r.ok)setDraft(null)})}><input type="hidden" name="id" value={draft==="new"?"":draft.id}/><label>Etiqueta<input name="label" defaultValue={draft==="new"?"Casa":draft.label}/></label><label>Región<select name="region" value={region} onChange={e=>setRegion(e.target.value)}>{chileRegions.map(r=><option key={r.id}>{r.name}</option>)}</select></label><label>Ciudad<select name="city" defaultValue={draft==="new"?"":draft.city} key={region}>{citiesForRegion(regionId).map(c=><option key={c}>{c}</option>)}</select></label><label>Calle<input name="street" required defaultValue={draft==="new"?"":draft.street}/></label><label>Número<input name="streetNumber" required defaultValue={draft==="new"?"":draft.streetNumber}/></label><label>Depto / casa<input name="detail" defaultValue={draft==="new"?"":draft.detail}/></label><label className="check-label"><input type="checkbox" name="isDefault" defaultChecked={draft!=="new"&&draft.isDefault}/> Dirección predeterminada</label><div className="table-actions"><button className="soft-button dark" disabled={busy}>{busy?"Guardando…":"Guardar dirección"}</button><button type="button" className="mini-action" onClick={()=>setDraft(null)}>Cancelar</button></div></form>}
 <h2>Cambiar contraseña</h2><form className="account-settings-form password-settings-form" action={(fd)=>start(async()=>feedback(await changeCustomerPassword(fd)))}><label>Contraseña actual<PasswordField name="currentPassword" autoComplete="current-password" required/></label><label>Nueva contraseña<PasswordField name="newPassword" autoComplete="new-password" minLength={12} required/><small>Mínimo 12 caracteres.</small></label><button className="soft-button dark" disabled={busy}>Actualizar contraseña</button></form>{notice&&<p className="success-message" role="status">{notice}</p>}{error&&<p className="error-message" role="alert">{error}</p>}</section>
}
